services:
    frontend:
        image: ghcr.io/qtchaos/vidbox-client:latest
        ports:
            - "0.0.0.0:80:4173"

    backend:
        image: ghcr.io/qtchaos/vidbox-server:latest
        ports:
            - "0.0.0.0:3000:3000"
