services:
    frontend:
        build:
            context: ./packages/client
        ports:
            - "0.0.0.0:80:4173"

    backend:
        build:
            context: ./packages/server
        ports:
            - "0.0.0.0:3000:3000"
