version: "3.8"

services:
    frontend:
        build:
            context: ./packages/client
        ports:
            - "127.0.0.1:80:4172"

    backend:
        build:
            context: ./packages/server
        ports:
            - "127.0.0.1:3000:3000"
