version: "3.8"

services:
    frontend:
        build:
            context: ./packages/client
            dockerfile: Dockerfile
        ports:
            - 80/tcp
        command: ["bun", "index.js"]

    backend:
        build:
            context: ./packages/server
            dockerfile: Dockerfile
        ports:
            - 3000/tcp
        command: ["bun", "run", "index.ts"]
