version: "3.8"

services:
    frontend:
        build:
            context: ./packages/client
            dockerfile: Dockerfile

    backend:
        build:
            context: ./packages/server
            dockerfile: Dockerfile
