services:
    frontend:
        build:
            context: ./packages/client
        ports:
            - "80:4173"

    backend:
        build:
            context: ./packages/server
        ports:
            - "3000:3000"
