name: Build and Publish Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Step 3: Build and push the server image
    - name: Build and Push Server Image
      run: |
        docker build ./packages/server -t ghcr.io/${{ github.repository_owner }}/vidbox-server:latest
        docker push ghcr.io/${{ github.repository_owner }}/vidbox-server:latest

    # Step 4: Build and push the client image
    - name: Build and Push Client Image
      run: |
        docker build ./packages/client -t ghcr.io/${{ github.repository_owner }}/vidbox-client:latest
        docker push ghcr.io/${{ github.repository_owner }}/vidbox-client:latest
